version: '3.8'

services:
  # Material Delivery Dashboard
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pkp-material-dashboard
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FLASK_DEBUG=False
      - DATABASE_URL=sqlite:///data/delivery_dashboard.db
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - N8N_TO_FLASK_API_KEY=${N8N_TO_FLASK_API_KEY}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_BASE_URL=${N8N_BASE_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - NOTIFICATION_EMAIL=${NOTIFICATION_EMAIL}
      - CURRENCY=${CURRENCY:-AED}
      - TIMEZONE=${TIMEZONE:-Asia/Dubai}
    volumes:
      - dashboard-data:/app/data
      - dashboard-uploads:/app/static/uploads
    networks:
      - pkp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # n8n Automation Platform (Optional - if self-hosting)
  n8n:
    image: n8nio/n8n:latest
    container_name: pkp-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USERNAME:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_HOST}
      - GENERIC_TIMEZONE=${TIMEZONE:-Asia/Dubai}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - pkp-network
    depends_on:
      - dashboard

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: pkp-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
    networks:
      - pkp-network
    depends_on:
      - dashboard
      - n8n

volumes:
  dashboard-data:
    driver: local
  dashboard-uploads:
    driver: local
  n8n-data:
    driver: local
  nginx-cache:
    driver: local

networks:
  pkp-network:
    driver: bridge
